name: Hello, World!

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Use a composite action
        uses: ./.github/actions/greeter

      - name: Use a composite action with a custom message
        uses: ./.github/actions/greeter
        with:
          greet: 'Hello, GH-Actions'

      - name: Use a composite action with conditional branching
        uses: ./.github/actions/branching

      - name: Repeat action with custom environment
        uses: ./.github/actions/branching
        with:
          environment: production
