name: Hello, World!

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Use a composite action
        uses: ./.github/actions/greeter.yml

      - name: Use a composite action with a custom message
        uses: ./.github/actions/greeter.yml
        with:
          greet: 'Hello, GH-Actions'
