name: Hello, World!

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

        uses: ./composite.yml
