name: Hello, World!

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  use_composite_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Greet with default message
        uses: ./.github/actions/greeter

      - name: Greet with a custom message
        uses: ./.github/actions/greeter
        with:
          greet: 'Hello, GH-Actions'

      - name: Branching with default environment
        uses: ./.github/actions/branching

      - name: Branching with custom environment
        uses: ./.github/actions/branching
        with:
          environment: production
